#!/usr/bin/env bash
# disable-services
# A wrapper that makes any module running inside it not start services once then are installed
# Written by Guy Sheffer <guysoft at gmail dot com> and Gina Häußge <osd@foosel.net>
# GPL V3
########
#
# RatOS override of CustomPiOS' built-in disable-services module - see
# start_chroot_script for why this override exists. Unchanged from upstream.
########
set -ex

rm -r /usr/sbin/policy-rc.d || true
