#!/usr/bin/env bash

# Source error handling, leave this in place
set -xe

# Source CustomPIOS common.sh
source /common.sh
install_cleanup_trap

echo_green "Installing RPI MCU service"

pushd "/home/${BASE_USER}/klipper"
echo "flashing rpi-mcu"
cp -f "/home/${BASE_USER}/printer_data/config/RatOS/boards/rpi/firmware.config" "/home/${BASE_USER}/klipper/.config"
make olddefconfig
make clean
# Reset ownership so make flash doesn't complain
chown "${BASE_USER}:${BASE_USER}" -R "/home/${BASE_USER}/klipper"
make flash
popd

pushd "/home/${BASE_USER}/klipper"
sudo cp "./scripts/klipper-mcu.service" /etc/systemd/system/klipper_mcu.service
sudo systemctl enable klipper_mcu.service
popd

# Reset ownership
chown "${BASE_USER}:${BASE_USER}" -R "/home/${BASE_USER}/klipper"
