#!/usr/bin/env bash
# Shebang for better file detection
#### RatOS module config
#### Written by Mikkel Schmidt aka miklschmidt <mikkel.schmidt@gmail.com>
#### Copyright 2023
####
#### Contains code from Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2021 - 2022
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

[ -n "$RATOS_CONFIG_SHIP" ] || RATOS_CONFIG_SHIP=https://github.com/Rat-OS/RatOS-configuration.git
[ -n "$RATOS_CONFIG_BRANCH" ] || RATOS_CONFIG_BRANCH=v2.1.x
[ -n "$RATOS_THEME_SHIP" ] || RATOS_THEME_SHIP=https://github.com/Rat-OS/RatOS-theme.git
[ -n "$RATOS_THEME_BRANCH" ] || RATOS_THEME_BRANCH=v2.1.x
# Temporarily pointed at a fork carrying the NetworkManager-based WiFi-join
# rewrite (add-wifi-network.sh used wpa_supplicant/wpa_cli directly, which
# doesn't work under current Raspberry Pi OS's default NetworkManager
# stack - same root cause as the hotspot module rewrite in this repo).
# Revert to Rat-OS/RatOS-configurator once that fix is merged upstream.
[ -n "$RATOS_CONFIGURATOR_SHIP" ] || RATOS_CONFIGURATOR_SHIP=https://github.com/mattmerritt215/RatOS-configurator.git
[ -n "$RATOS_CONFIGURATOR_BRANCH" ] || RATOS_CONFIGURATOR_BRANCH=fix/networkmanager-wifi

#### NOTE:
#### python3-serial is a klipper requirement
#### python3-opencv is needed for moonraker-obico by obico in version 2.0

[ -n "$RATOS_DEPS" ] || RATOS_DEPS="python3-serial python3-opencv"